name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install coverage  # For test coverage

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Install Xvfb to simulate a display for Tkinter and run tests with coverage
    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run tests with coverage in virtual display
      run: |
        xvfb-run -a coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml  # Ensure you generate coverage.xml with coverage.py

  build-release:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executables
      run: |
        if [ $RUNNER_OS == 'Linux' ]; then
          pyinstaller --onefile main.py
          mv dist/main ./dist/main_linux
        elif [ $RUNNER_OS == 'macOS' ]; then
          pyinstaller --onefile main.py
          mv dist/main ./dist/main_macos
        elif [ $RUNNER_OS == 'Windows' ]; then
          pyinstaller --onefile main.py
          mv dist/main.exe ./dist/main_windows.exe
        fi

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Release ${{ github.event.release.tag_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.os == 'Windows' && './dist/main_windows.exe' || matrix.os == 'macOS' && './dist/main_macos' || './dist/main_linux' }}
        asset_name: ${{ matrix.os == 'Windows' && 'main_windows.exe' || matrix.os == 'macOS' && 'main_macos' || 'main_linux' }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
